

select * from TRAVELGE_INFO;

select * from TRAVELGE_RECOMMANDATION;

alter table TRAVELGE_RECOMMANDATION ADD (READ_NUM NUMBER(10));

alter table TRAVELGE_RECOMMANDATION ADD (RECOMMANDATION_DATE date);

commit